### ISSUE TITLE
Update Rstudio for DE container

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Rstudio-rnaseq-contained#1]
- [x] Containerised 
- [x] Code review
- [ ] On dockerhub
- [ ] Version controlled

**Comment by nandan75** [comment]
- The singularity container was successfully updated using the methods documented  in https://github.com/Sydney-Informatics-Hub/Rstudio-rnaseq-contained 
- The docker recipe file https://github.com/Sydney-Informatics-Hub/rnaseqOct23_Testing/blob/Nandan/Scripts/Day2/BioCommons_Dockerfile_4.1.0_V4.0 was used

**Comment by georgiesamaha** [comment]
@nandan75 please upload to SIH dockerhub

**Comment by nandan75** [comment]
https://hub.docker.com/repository/docker/sydneyinformaticshub/rnaseq-rstudio/general
