### ISSUE TITLE
Publish the final version of Rstudio for DE container

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/Rstudio-rnaseq-contained#3]
- Confirm that this is the final version
- Publish on dockerhub
- Save to github https://github.com/Sydney-Informatics-Hub/Rstudio-rnaseq-contained

**Comment by georgiesamaha** [comment]
- [x] Dockerfile on github https://github.com/Sydney-Informatics-Hub/Rstudio-rnaseq-contained
- [x] Push to dockerhub following dockerhub instructions 
- [x] Replicate what has been done for other containers on SIH dockerhub

**Comment by nandan75** [comment]
Completed
(https://hub.docker.com/repository/docker/sydneyinformaticshub/rnaseq-rstudio/general)
